# roles/headlamp/tasks/main.yml
- name: Ensure namespace exists
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    api_version: v1
    kind: Namespace
    name: "{{ headlamp_namespace }}"
    state: present

- name: Add Headlamp Helm repo
  kubernetes.core.helm_repository:
    name: headlamp
    repo_url: "https://kubernetes-sigs.github.io/headlamp/"

- name: Deploy / upgrade Headlamp
  kubernetes.core.helm:
    name: "{{ headlamp_release_name }}"
    chart_ref: "headlamp/headlamp"
    chart_version: "{{ headlamp_chart_version | default(omit) }}"
    release_namespace: "{{ headlamp_namespace }}"
    kubeconfig: "{{ kubeconfig_path }}"
    values_files:
      - "{{ playbook_dir }}/../files/values-headlamp.yaml"
    create_namespace: false
    wait: true
    atomic: true
