# playbooks/deploy_headlamp.yml
- name: Deploy Headlamp to the cluster
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../group_vars/k8s.yml
  roles:
    - roles/headlamp
